### ISSUE TITLE
Can no longer copy/paste a graphic into Tweetdeck

### ISSUE THREAD

**Issue by manixdk** [dimdenGD/OldTweetDeck#275] opened 2024-05-31 07:40 UTC
Include version of extension. **Make sure you're using last version before submitting a bug report! Check releases page before reporting anything!** OldTweetDeck
3.6.4 Can't copy/past a graphic any longer.

**Comment by dimdenGD** [comment] 2024-05-31 07:41
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/87

**Closed by dimdenGD** 2024-05-31 07:41 UTC
Labels: bug
