### ISSUE TITLE
"Linking another account you own" doesn't work

### ISSUE THREAD

**Issue by alphajaunevert** [dimdenGD/OldTweetDeck#347] opened 2024-10-02 01:45 UTC
I found that when I click it, it says "Rate limit exceeded" still on 4.0.3.
![image](https://github.com/user-attachments/assets/d8f8a2f8-61c8-4897-8514-e340956d4e93)

**Comment by dimdenGD** [comment] 2024-10-02 09:02
duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/259

**Closed by dimdenGD** 2024-10-02 09:02 UTC
Labels: bug
