### ISSUE TITLE
Only some columns loading

### ISSUE THREAD

**Issue by forestpassineau** [dimdenGD/OldTweetDeck#36] opened 2023-08-23 16:56 UTC
Was working great until now but just this morning it fails to load many of the user profile columns I have setup that were loading fine yesterday.  Tried updating to newest 2.0.5 version and still only loads some of the user profile columns and many are left unpopulated?

**Comment by dimdenGD** [comment] 2023-08-23 18:06
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/34

**Closed by dimdenGD** 2023-08-23 18:06 UTC

**Comment by dimdenGD** [comment] 2023-08-23 22:37
Released new version, update!
