### ISSUE TITLE
'Link another account you own' doesn't work

### ISSUE THREAD

**Issue by ehdqlfehdzbf** [dimdenGD/OldTweetDeck#291] opened 2024-06-25 02:42 UTC
![image](https://github.com/dimdenGD/OldTweetDeck/assets/173752224/90a07609-e5e4-44f4-8284-a69d66863918)

I'm using Chrome. and version is OldTweetDeck 3.6.4.
'Link another account you own' doesn't work.

**Comment by dimdenGD** [comment] 2024-06-25 11:49
Duplicate of #259

**Closed by dimdenGD** 2024-06-25 11:49 UTC
Labels: bug
