### ISSUE TITLE
Unable to load Tweetdeck

### ISSUE THREAD

**Issue by membrant** [dimdenGD/OldTweetDeck#256] opened 2024-05-20 17:43 UTC
When I go to the URL (https://x.com/i/tweetdeck), it immediately redirects me to 

https://x.com/i/tweetdeck?failedScript=vendor   and it shows

![image](https://github.com/dimdenGD/OldTweetDeck/assets/145082724/031f2528-4df0-4468-baf7-41e1195d069d)

I have the latest update from 3 days ago.

**Comment by K0nja** [comment] 2024-05-20 17:44
I get the same issue, Twitter/Elon/X must have changed something

**Comment by mergederg** [comment] 2024-05-20 17:48
I had this happening briefly ten or fifteen minutes ago but then it went away and everything was working again.  🤷

**Comment by Lordmau5** [comment] 2024-05-20 17:49
Had the same thing happen here just now, a Ctrl+F5 (or Cmd+F5 on Mac I think?) fixed it for me

**Comment by membrant** [comment] 2024-05-20 17:51
No such luck with refresh for me :(

**Comment by rjdoerz** [comment] 2024-05-20 18:07
Same. Was having this issue a few days ago when the latest update (3.6.2) fixed it. But now the issue is back and refreshing doesn't seem to do anything. 
I'm using Firefox.

**Comment by PowerOfRed17** [comment] 2024-05-20 18:55
Having the same issue. I had a similar issue for a little bit after updating to 3.6.2 but that ended up being a conflict with the Disconnect add-on in Firefox and disabling that fixed it. This is something different and no combination of disabling add-ons or changing tracking protection is fixing it.

**Comment by SammyP41** [comment] 2024-05-20 19:16
I'm having the same issue. It says "Hmmm... This page doesn't exist. Try searching. for something else" Does anyone know the solution? Do I need to reinstall everything or reinstall something new?

**Comment by WhereTheTimeWent** [comment] 2024-05-20 19:19
Can confirm, accessing TweetDeck via https://x.com/i/tweetdeck doesn't work anymore.
It worked fine before I reloaded. Didn't have this before.

**Comment by SammyP41** [comment] 2024-05-20 19:23
> Had the same thing happen here just now, a Ctrl+F5 (or Cmd+F5 on Mac I think?) fixed it for me

Is it still working for you? If so, would love if you could try to help us out

**Comment by naanlizard** [comment] 2024-05-20 19:32
Also broken here, tried hard refreshing, disabling other extensions, etc nothing working. Good luck dmiden

**Comment by archeruwu** [comment] 2024-05-20 19:41
Update to latest release on the releases tab, should be fixed now

**Comment by dimdenGD** [comment] 2024-05-20 19:41
New update out

**Comment by PowerOfRed17** [comment] 2024-05-20 19:47
Working perfectly now, thank you!

**Closed** 2024-05-20 19:49 UTC

**Comment by SammyP41** [comment] 2024-05-20 19:57
Can someone give me directions on what exactly to do?

**Comment by archeruwu** [comment] 2024-05-20 19:59
> Can someone give me directions on what exactly to do?

Go to the main repo, and follow the install guide there to update https://github.com/dimdenGD/OldTweetDeck

**Comment by Mylad79190** [comment] 2024-05-20 20:47
Thanks

**Comment by membrant** [comment] 2024-05-21 11:53
I'm still having the same issue. I am using Edge browser, so took the latest Chromium zip file. 
But maybe it's something else, 'coz even when I type in https://www.x.com, it just redirects me to https://[x.com/?failedScript=vendor](https://x.com/?failedScript=vendor)

Has anyone resolved this issue?

**Comment by Brezenabsalzer** [comment] 2024-05-22 06:57
> I'm still having the same issue. I am using Edge browser, so took the latest Chromium zip file. But maybe it's something else, 'coz even when I type in https://www.x.com, it just redirects me to https://[x.com/?failedScript=vendor](https://x.com/?failedScript=vendor)
> 
> I have deleted the extension. reinstalled it per directions. Cleared cache, cookies. Hasn't resolved the issue. Has anyone resolved this issue?

I guess you have the "strict" "Do not track" enabled (I don't know the exact term, because I am using the german version of Edge). Set the option to the middle one ("Ausgewogen") and do a reload. Then it should work again.

**Comment by membrant** [comment] 2024-05-23 00:09
> https://x.com/i/tweetdeck

Thank you, that helped!
