### ISSUE TITLE
Anyone esle 

### ISSUE THREAD

**Issue by ItsBluey** [dimdenGD/OldTweetDeck#191] opened 2024-02-15 03:47 UTC
![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/290efff1-b4d3-4be1-a427-2a29840a7213)
didnt have this until rn now was working just fine and i reinstalled still

**Comment by hofleverancier** [comment] 2024-02-15 06:31
Same here, 3.2.3 seems to have been broken.

**Comment by surapunoyousei** [comment] 2024-02-15 10:49
No. Some of TweetDeck APIs are deleted by X.

Please delete this post. Do not waste maintainer's time

**Comment by mattweeden** [comment] 2024-02-15 11:20
Getting the same issue

**Comment by dimdenGD** [comment] 2024-02-15 11:29
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/188

**Closed by dimdenGD** 2024-02-15 11:29 UTC
