### ISSUE TITLE
Link another account you own fails.

### ISSUE THREAD

**Issue by enustah28** [dimdenGD/OldTweetDeck#334] opened 2024-08-31 14:07 UTC
{"errors":[{"message":"Bad Authentication data","code":215}]}

"This message is displayed, and I am unable to register a new account."

**Comment by dimdenGD** [comment] 2024-08-31 14:07
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/259

**Closed by dimdenGD** 2024-08-31 14:07 UTC
Labels: bug
