### ISSUE TITLE
Link another account error

### ISSUE THREAD

**Issue by minsu-kim-digipen** [dimdenGD/OldTweetDeck#295] opened 2024-06-28 02:56 UTC
### Version
3.6.4 

### Error picture
When I click `Link another account you own`, authentication error occurs.
![스크린샷 2024-06-28 115534](https://github.com/dimdenGD/OldTweetDeck/assets/80092494/dfaf5c5e-51e9-47a8-bda3-20fa29a95e30)

**Comment by katabame** [comment] 2024-06-28 05:20
duplicate of #259

**Closed** 2024-06-28 12:00 UTC
Labels: bug
