### ISSUE TITLE
Unable to Add Account to Teams

### ISSUE THREAD

**Issue by peachouji** [dimdenGD/OldTweetDeck#308] opened 2024-07-16 06:42 UTC
it used to completely not load, but now the log in loads, but when you go to authorize the account, the page refreshes and nothing happens. doesn't matter how many times you do it.

**Comment by shinaisms** [comment] 2024-07-31 15:06
Rate limit exceeded

**Comment by z411** [comment] 2024-08-09 02:20
Porbably duplicate of #259? Same issue here.

**Closed** 2024-08-09 08:57 UTC
Labels: bug
