### ISSUE TITLE
Version 2.0 does NOT work.

### ISSUE THREAD

**Issue by NotScooty** [dimdenGD/OldTweetDeck#13] opened 2023-08-19 17:52 UTC
Uninstalled 1.0.2 and downloaded 2.0 and it prompts me back to buying premium.

**Comment by dimdenGD** [comment] 2023-08-19 17:52
Which browser

**Comment by NotScooty** [comment] 2023-08-19 17:54
Chrome. Fresh install as well.

**Comment by dimdenGD** [comment] 2023-08-19 17:54
I just installed Chrome and 2.0 extension on it 3 minutes ago and it worked fine

**Comment by vitumen** [comment] 2023-08-19 17:56
Same here. Version 1.0.2 was working well. Now with 2.0 it took me to Buy premium

**Comment by AdamMReese** [comment] 2023-08-19 17:57
It's not working for me, either.  I'm on Microsoft Edge version 116.0.1938.54 (Official build) beta (64-bit).

**Comment by piovsn** [comment] 2023-08-19 17:59
Same here on chrome. Chrome throws up an error which links to this page https://developer.chrome.com/blog/mv2-transition/ "January 2023: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions."

**Comment by WhereTheTimeWent** [comment] 2023-08-19 18:00
It's working fine on my end. Google Chrome 116.0.5845.97. "Updated" from 1.0.2 (loaded 2.0.0 and removed 1.0.2 manually).

**Comment by dimdenGD** [comment] 2023-08-19 18:00
Works fine on both Edge and Chrome for me

**Comment by NotScooty** [comment] 2023-08-19 18:01
Since I can't get 2.0.0 to work should I stick to 1.0.2 or should I try to work around it.

**Comment by AdamMReese** [comment] 2023-08-19 18:02
> Same here on chrome. Chrome throws up an error which links to this page https://developer.chrome.com/blog/mv2-transition/ "January 2023: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions."

Check the updated version of that blog post. That got postponed.

**Comment by AdamMReese** [comment] 2023-08-19 18:06
Okay, I think it's a caching issue. I removed all the cookie and cache data for the Twitter website and reloaded, and it's working now. Everyone else can see if that works for them as well.

**Comment by piovsn** [comment] 2023-08-19 18:13
Clearing cache and cookies did not fix it for me unfortunately.

**Comment by AdamMReese** [comment] 2023-08-19 18:14
Yeah, my brother is saying the same thing. It's strange, since it worked for me.

**Comment by Uron0238** [comment] 2023-08-19 18:16
Thank you for creating this browser extension.
Does BTD support version 2.0.0?
In my environment (Chrome), when I open the tweet input field, certain actions like scrolling become impossible.

**Comment by dimdenGD** [comment] 2023-08-19 18:48
Updated again, try if it works now

**Comment by lcreed** [comment] 2023-08-19 18:53
that latest pull fixed it again on brave.  It is NOW working with shields up.  Thanks!!!  

Anyone got the btd plugin working with this?

**Comment by AdamMReese** [comment] 2023-08-19 18:54
After a few attempts, I got it to go back to TweetDeck, but it's still showing the new TweetDeck UI underneath and I can't compose a new tweet without it [activating the UI underneath it with the flashing cursor](https://i.imgur.com/ybFGyCo.png).

**Comment by dimdenGD** [comment] 2023-08-19 18:58
> After a few attempts, I got it to go back to TweetDeck, but it's still showing the new TweetDeck UI underneath and I can't compose a new tweet without it [activating the UI underneath it with the flashing cursor](https://i.imgur.com/ybFGyCo.png).

Updated, try latest version if it fixes this

**Comment by xtommas** [comment] 2023-08-19 19:34
Not working for me on Firefox Nightly. Chromes works fine

**Comment by piovsn** [comment] 2023-08-19 19:38
Working now on chrome, and the better tweetdeck works too. Thanks Dimden! Much appreciated.

**Comment by lcreed** [comment] 2023-08-19 19:44
any secrets to get btd working?

**Comment by piovsn** [comment] 2023-08-19 19:49
are you using dimden's forked version? it's linked at the bottom of the readme

**Comment by lcreed** [comment] 2023-08-19 19:50
Ahh, didn't see that.  Let me grab it and try.  Thank you!

**Comment by lcreed** [comment] 2023-08-19 19:58
Downloaded the Chrome.zip for BTD and dragged it into my Brave Extensions.  Its throwing this error:

![image](https://github.com/dimdenGD/OldTweetDeck/assets/734957/5d964f24-dc68-4e65-99cd-6bf94a524570)

**Comment by dimdenGD** [comment] 2023-08-19 20:00
Don't pay attention to errors, I get that error too all the time and it works fine

**Comment by lcreed** [comment] 2023-08-19 20:01
interesting that i suddenly got an update btd had been updated and now its working.  Thanks so much!

**Comment by Uron0238** [comment] 2023-08-19 21:10
Version 1.0.2 works fine, but starting from 2.0, it doesn't function properly after opening the tweet input field. When hovering over the sidebar, a popup similar to the column names appears in the upper-left corner of the screen. Is there any correlation between these occurrences?
![image](https://github.com/dimdenGD/OldTweetDeck/assets/9503303/56cd3390-33a8-4c1f-9289-2b27e252ac63)

**Comment by AdamMReese** [comment] 2023-08-19 22:01
Yeah, I had to switch back to 1.0.2 because I kept having that issue where the newer TweetDeck UI kept overlapping everything, even after clearing the cache. Hopefully it gets resolved soon.

**Comment by CR0077** [comment] 2023-08-19 22:09
I use Chrome and it didn't work for me at all, got Edge and it worked for a while until it didn't and now I got Opera and it works for now. The errors just randomly appear after closing the browser and it stops working.

**Comment by arika0093** [comment] 2023-08-20 01:35
> Version 1.0.2 works fine, but starting from 2.0, it doesn't function properly after opening the tweet input field. When hovering over the sidebar, a popup similar to the column names appears in the upper-left corner of the screen. Is there any correlation between these occurrences? ![image](https://user-images.githubusercontent.com/9503303/261820415-56cd3390-33a8-4c1f-9289-2b27e252ac63.png)

I share this because I had a similar problem and solved it.

I don't know why, but it seems to be caused by the `body::before` element covering the entire screen and making it impossible to use.
The solution is to disable it by adding the following CSS to BetterTD's custom CSS.
```css
body:before {
    position: relative !important;
}
```

Browser: Google Chrome
OldTweetdeck: v2.0.1
BetterTD: v4.11.1

**Comment by Fapo39** [comment] 2023-08-20 05:03
Firefox / Firefox ESR, can't get 2.0.1 to work just takes me to buy page and this was after wiping cache and even starting new profile; v1.02 would say it's corrupted

**Comment by ItsBradaz** [comment] 2023-08-20 05:58
Opera, neither 2.0.1/1.0.2 work anymore. Just redirects to tweetdeck login page with "Log in with your Twitter account
Sorry, something went wrong. Please try again later." even after pressing login.

**Comment by codelioness** [comment] 2023-08-20 13:02
Firefox, 2.0.1 is only redirecting to /i/premium_sign_up for me as well. Clearing cache and cookies for Twitter didn't work.

**Comment by kururuchan** [comment] 2023-08-20 14:38
It seems to be working on and off. About 10 minutes ago I was getting the re-direct, but now it's working again.

**Comment by kleusbalut** [comment] 2023-08-21 11:21
> I share this because I had a similar problem and solved it.
> 
> I don't know why, but it seems to be caused by the `body::before` element covering the entire screen and making it impossible to use. The solution is to disable it by adding the following CSS to BetterTD's custom CSS.
> 
> ```css
> body:before {
>     position: relative !important;
> }
> ```

Thank you for making a great Chrome extension.
I used Stylus and the same code worked.

Japanese:
素晴らしいChrome拡張を作ってくださり、ありがとうございます。
私はStylusを使用して、同じコードで機能しました。

```css
@-moz-document url-prefix("https://tweetdeck.twitter.com/") {
    body:before {
        position: relative !important;
    }
}
```

Browser: Vivaldi 6.1.3035.100 (Stable channel) (64-bit)
OldTweetdeck: v2.0.1
Stylus: v1.5.33

**Closed** 2023-08-29 17:46 UTC
